package backup

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"filippo.io/age"
	"github.com/stretchr/testify/require"
)

// A throwaway pair, generated by the age library for these tests, that the
// settings screen's key generator is checked against
// (frontend/src/lib/ageKeys.test.ts holds the same pair).
const (
	referenceIdentity  = "AGE-SECRET-KEY-15WVA2EEQZFV75G9LJENM2PVQS9M3WURETAGJXX4PEMUVLWW40V7SXLFC3W"
	referenceRecipient = "age1n946z2m9xyhkwem4vn9yj7hj7trelehnwv6q09vqqkzfq4sz3v8qp6rp0m"
)

func TestTheReferencePairIsAPair(t *testing.T) {
	identity, err := age.ParseX25519Identity(referenceIdentity)
	require.NoError(t, err)
	require.Equal(t, referenceRecipient, identity.Recipient().String())
}

func TestASealedPartOpensOnlyWithItsIdentity(t *testing.T) {
	mine, err := age.GenerateX25519Identity()
	require.NoError(t, err)
	theirs, err := age.GenerateX25519Identity()
	require.NoError(t, err)
	recipients, _, err := parseRecipients([]string{mine.Recipient().String(), referenceRecipient})
	require.NoError(t, err)

	var sealed bytes.Buffer
	w, err := seal(&sealed, recipients)
	require.NoError(t, err)
	_, err = w.Write([]byte("an invented dump"))
	require.NoError(t, err)
	require.NoError(t, w.Close())
	require.NotContains(t, sealed.String(), "an invented dump")

	plain, err := open(bytes.NewReader(sealed.Bytes()), true, []age.Identity{mine})
	require.NoError(t, err)
	var got bytes.Buffer
	_, err = got.ReadFrom(plain)
	require.NoError(t, err)
	require.Equal(t, "an invented dump", got.String())

	reference, err := ReadIdentities(strings.NewReader("# created by a test\n"+referenceIdentity+"\n"), nil)
	require.NoError(t, err)
	_, err = open(bytes.NewReader(sealed.Bytes()), true, reference)
	require.NoError(t, err, "either recipient's identity opens it")

	_, err = open(bytes.NewReader(sealed.Bytes()), true, []age.Identity{theirs})
	require.ErrorIs(t, err, ErrWrongIdentity)
	_, err = open(bytes.NewReader(sealed.Bytes()), true, nil)
	require.ErrorIs(t, err, ErrIdentityRequired)
}

func TestWithNoRecipientsAPartIsPlaintext(t *testing.T) {
	var out bytes.Buffer
	w, err := seal(&out, nil)
	require.NoError(t, err)
	_, _ = w.Write([]byte("plain"))
	require.NoError(t, w.Close())
	require.Equal(t, "plain", out.String())
}

func TestAMalformedKeyIsNoRecipient(t *testing.T) {
	_, err := ParseRecipient(referenceRecipient)
	require.NoError(t, err)
	for _, bad := range []string{"", "age1", "ssh-ed25519 AAAA", referenceIdentity} {
		_, err := ParseRecipient(bad)
		require.Error(t, err, bad)
	}
	_, err = ReadIdentities(strings.NewReader(referenceRecipient), nil)
	require.Error(t, err)
}

func TestTheKeyIDNamesAKeyWithoutRevealingIt(t *testing.T) {
	require.Len(t, KeyID("a"), 16)
	require.Equal(t, KeyID("a"), KeyID("a"))
	require.NotEqual(t, KeyID("a"), KeyID("b"))
	require.NotContains(t, KeyID("an-invented-key"), "invented")
}

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for name, body := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
		require.NoError(t, os.WriteFile(path, []byte(body), 0o600))
	}
}

func readTree(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	require.NoError(t, filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		require.NoError(t, err)
		if info.Mode().IsRegular() {
			rel, _ := filepath.Rel(root, path)
			data, _ := os.ReadFile(path)
			out[filepath.ToSlash(rel)] = string(data)
		}
		return nil
	}))
	return out
}

func TestAttachmentsRoundTripThroughASealedArchive(t *testing.T) {
	source := t.TempDir()
	writeTree(t, source, map[string]string{
		"space-a/receipt.pdf":       "pdf bytes",
		"space-b/nested/photo.jpg":  "jpg bytes",
		".restore-1/left-over.pdf":  "staging",
		".before-restore-1/old.pdf": "set aside",
		"top-level.txt":             "top",
	})
	identity, err := age.GenerateX25519Identity()
	require.NoError(t, err)
	recipients, _, _ := parseRecipients([]string{identity.Recipient().String()})

	dir := t.TempDir()
	file, err := writePart(dir, "attachments.tar.gz.age", recipients, func(w io.Writer) (File, error) {
		return tarAttachments(source, w)
	})
	require.NoError(t, err)
	require.Equal(t, 3, file.Count, "a restore's working directories are not backed up")

	one := Set{Dir: dir, Intact: true}
	one.Encrypted = true
	one.Files = map[Part]File{PartAttachments: file}
	target := t.TempDir()
	count, err := readAttachments(one, []age.Identity{identity}, target)
	require.NoError(t, err)
	require.Equal(t, 3, count)
	require.Equal(t, map[string]string{
		"space-a/receipt.pdf":      "pdf bytes",
		"space-b/nested/photo.jpg": "jpg bytes",
		"top-level.txt":            "top",
	}, readTree(t, target))

	info, err := os.Stat(filepath.Join(dir, "attachments.tar.gz.age"))
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0o600), info.Mode().Perm())
}

func TestAChangedFileFailsItsChecksum(t *testing.T) {
	dir := t.TempDir()
	file, err := writePart(dir, "database.sqlite", nil, func(w io.Writer) (File, error) {
		_, err := w.Write([]byte("dump"))
		return File{}, err
	})
	require.NoError(t, err)
	one := Set{Dir: dir}
	one.Name = "s"
	one.Files = map[Part]File{PartDatabase: file}
	require.NoError(t, Checksum(one, PartDatabase))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "database.sqlite"), []byte("dumb"), 0o600))
	require.ErrorContains(t, Checksum(one, PartDatabase), "has changed")
}

func tarOf(t *testing.T, names ...string) []byte {
	t.Helper()
	var out bytes.Buffer
	gz := gzip.NewWriter(&out)
	tw := tar.NewWriter(gz)
	for _, name := range names {
		require.NoError(t, tw.WriteHeader(&tar.Header{Name: name, Mode: 0o600, Size: 1, Typeflag: tar.TypeReg}))
		_, _ = tw.Write([]byte("x"))
	}
	require.NoError(t, tw.Close())
	require.NoError(t, gz.Close())
	return out.Bytes()
}

func TestAnArchiveEntryOutsideItsDirectoryIsRefused(t *testing.T) {
	for _, name := range []string{"attachments/../../etc/passwd", "/etc/passwd", "elsewhere/file", "attachments/a/../../x"} {
		err := walkTar(bytes.NewReader(tarOf(t, name)), "attachments", func(string, *tar.Header, io.Reader) error {
			return nil
		})
		require.Error(t, err, name)
	}
	var seen []string
	err := walkTar(bytes.NewReader(tarOf(t, "./attachments/a.pdf", "attachments/b/c.pdf")), "attachments",
		func(rel string, _ *tar.Header, _ io.Reader) error {
			seen = append(seen, rel)
			return nil
		})
	require.NoError(t, err)
	require.Equal(t, []string{"a.pdf", "b/c.pdf"}, seen)
}

func TestTheSecretsArchiveNamesWhatItCouldNotRead(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root reads a 0000 file, so there is nothing unreadable to name")
	}
	dir := t.TempDir()
	writeTree(t, dir, map[string]string{"SECRET_KEY": "k", "DATABASE_URL": "u"})
	require.NoError(t, os.WriteFile(filepath.Join(dir, "POSTGRES_PASSWORD"), []byte("p"), 0o000))
	var out bytes.Buffer
	file, err := tarSecrets(dir, &out)
	require.NoError(t, err)
	require.Equal(t, []string{"DATABASE_URL", "SECRET_KEY"}, file.Names)
	require.Equal(t, []string{"POSTGRES_PASSWORD"}, file.Skipped)
}

func TestListReadsSetsAndDamage(t *testing.T) {
	dir := t.TempDir()
	write := func(name string, manifest Manifest, files map[string]string) {
		setDir := filepath.Join(dir, name)
		require.NoError(t, os.MkdirAll(setDir, 0o700))
		writeTree(t, setDir, files)
		require.NoError(t, writeManifest(setDir, manifest))
	}
	at := time.Date(2026, 3, 3, 3, 30, 0, 0, time.UTC)
	write("2026-03-03_033000_nightly", Manifest{
		Format: FormatVersion, CreatedAt: at, Trigger: TriggerNightly, Encrypted: true,
		Files: map[Part]File{PartDatabase: {Path: "database.sqlite.age", Bytes: 4}},
	}, map[string]string{"database.sqlite.age": "abcd"})
	write("2026-03-04_033000_nightly", Manifest{
		Format: FormatVersion, CreatedAt: at.AddDate(0, 0, 1), Trigger: TriggerNightly,
		Files: map[Part]File{PartDatabase: {Path: "database.sqlite.age", Bytes: 9}},
	}, map[string]string{"database.sqlite.age": "short"})
	write("2026-03-02_033000_nightly", Manifest{
		Format: 1, CreatedAt: at.AddDate(0, 0, -1), Trigger: TriggerNightly,
		Files: map[Part]File{PartDatabase: {Path: "database.dump", Bytes: 4}},
	}, map[string]string{"database.dump": "abcd"})
	writeTree(t, dir, map[string]string{
		".partial-2026-03-05_033000_nightly/database.sqlite.age": "half",
		"unrelated.txt": "x",
	})

	sets, err := List(dir)
	require.NoError(t, err)
	require.Len(t, sets, 3)
	require.Equal(t, "2026-03-04_033000_nightly", sets[0].Name)
	require.False(t, sets[0].Intact)
	require.Contains(t, sets[0].Problem, "not the 9 recorded")
	require.True(t, sets[1].Intact)
	require.True(t, sets[1].Encrypted)
	require.Equal(t, "2026-03-02_033000_nightly", sets[2].Name)
	require.False(t, sets[2].Intact, "a Postgres-era set cannot be restored")
	require.Contains(t, sets[2].Problem, "Postgres dump")

	missing, err := List(filepath.Join(dir, "nowhere"))
	require.NoError(t, err)
	require.Empty(t, missing)
}

func TestPruneDeletesOldSets(t *testing.T) {
	dir := t.TempDir()
	now := time.Now()
	recent := filepath.Join(dir, "recent")
	require.NoError(t, os.MkdirAll(recent, 0o700))
	writeTree(t, recent, map[string]string{"database.sqlite": "d"})
	require.NoError(t, writeManifest(recent, Manifest{Format: FormatVersion, CreatedAt: now,
		Files: map[Part]File{PartDatabase: {Path: "database.sqlite", Bytes: 1}}}))
	old := filepath.Join(dir, "old")
	require.NoError(t, os.MkdirAll(old, 0o700))
	writeTree(t, old, map[string]string{"database.sqlite": "d"})
	require.NoError(t, writeManifest(old, Manifest{Format: FormatVersion, CreatedAt: now.AddDate(0, 0, -30),
		Files: map[Part]File{PartDatabase: {Path: "database.sqlite", Bytes: 1}}}))

	removed, err := Prune(dir, now, 14)
	require.NoError(t, err)
	require.ElementsMatch(t, []string{"old"}, removed)
	left, err := os.ReadDir(dir)
	require.NoError(t, err)
	require.Len(t, left, 1)
	require.Equal(t, "recent", left[0].Name())
}
