/**
 * Whole rows for tests, with every field the type asks for. A test names only
 * the fields its case turns on; the defaults are an ordinary, settled,
 * uncategorised row.
 */

import { ZERO_MONEY, moneyFromCents } from '@/lib/money'
import type {
  AccountWithBalances,
  Category,
  Transaction,
  Uuid,
} from '@/lib/transactions/types'

export function category(
  id: Uuid,
  name: string,
  parentId: Uuid | null = null,
  extra: Partial<Category> = {},
): Category {
  return {
    id,
    parent_id: parentId,
    name,
    kind: 'expense',
    known_category_id: null,
    txf_id: null,
    txf_ids: [],
    is_user_assignable: true,
    is_editable: true,
    protected_reason: null,
    excluded_from_reports: false,
    excluded_from_spending_plan: false,
    excluded_from_category_list: false,
    sort_order: 0,
    ...extra,
  }
}

export function transaction(overrides: Partial<Transaction> = {}): Transaction {
  return {
    id: 't1',
    account_id: 'a1',
    date: '2026-08-21',
    effective_date: null,
    amount: moneyFromCents(-1_850),
    currency: 'USD',
    amount_primary: null,
    fx_rate_used: null,
    statement_name: 'SQ *COFFEE XXXXXX1234',
    memo: '',
    transacted_on: null,
    payee: 'Harbor Coffee',
    notes: null,
    check_number: null,
    category_id: null,
    source: 'sync',
    is_pending: false,
    is_reviewed: false,
    excluded_from_reports: false,
    excluded_from_spending_plan: false,
    is_bill: false,
    is_subscription: false,
    transfer_pair_id: null,
    padded_txn_id: null,
    padding_txn_id: null,
    user_flag: null,
    user_flag_note: null,
    series_id: null,
    series_due_on: null,
    balance: null,
    splits: [],
    tag_ids: [],
    attachment_count: 0,
    receipt_status: null,
    receipt_not_needed: false,
    checking_category: false,
    category_checked_at: null,
    category_check_note: '',
    category_check_run_id: null,
    suggestion: null,
    ...overrides,
  }
}

export function account(overrides: Partial<AccountWithBalances> = {}): AccountWithBalances {
  return {
    id: 'a1',
    name: 'Everyday Checking',
    description: null,
    notes: null,
    kind: 'cash',
    type: 'checking',
    currency: 'USD',
    institution_id: null,
    connection_id: null,
    masked_number: null,
    logo_url: null,
    custom_logo_url: null,
    sort_order: 0,
    provider_balance: null,
    provider_balance_at: null,
    withheld_balance: null,
    withheld_balance_at: null,
    withheld_balance_reason: '',
    accept_zero_balance: false,
    opening_balance: ZERO_MONEY,
    opening_balance_on: null,
    goal_balance: ZERO_MONEY,
    pending_holds: ZERO_MONEY,
    credit_limit: null,
    statement_balance: null,
    minimum_due: null,
    due_date: null,
    interest_rate: null,
    statement_close_day: null,
    excluded_from_reports: false,
    excluded_from_spending_plan: false,
    excluded_from_account_bar: false,
    include_in_net_worth: true,
    exclude_bank_pending: false,
    requires_receipts: false,
    is_closed: false,
    closed_on: null,
    simplefin_account_id: null,
    sync_floor_on: null,
    history_starts_on: null,
    hide_below_balance: null,
    default_register_tab: null,
    property_address: null,
    vehicle_vin: null,
    vehicle_mileage: null,
    vehicle_mileage_as_of: null,
    vehicle_miles_per_year: null,
    valuation_source: null,
    valued_at: null,
    secured_by_account_id: null,
    balances: {
      balance: ZERO_MONEY,
      balance_with_pending: ZERO_MONEY,
      available_balance: ZERO_MONEY,
      credit_used_pct: null,
    },
    equity: null,
    ...overrides,
  }
}
