/** Matches auth.MinPasswordLength; the server is the one that enforces it. */
export const MIN_PASSWORD_LENGTH = 10

/** Counted in characters, as the server counts runes, not UTF-16 units. */
export function passwordLongEnough(password: string): boolean {
  return [...password].length >= MIN_PASSWORD_LENGTH
}

/** An admin form's password: generated by the server, or typed and long enough. */
export function chosenPasswordReady(generate: boolean, password: string): boolean {
  return generate || passwordLongEnough(password)
}
